export const ImgTool = [
    {id: 1, src:'./Tools/canva.svg', alt:'Canva'},
    {id: 2, src:'./Tools/clickup.svg', alt:'ClickUp'},
    {id: 3, src:'./Tools/docker.svg', alt:'Docker'},
    {id: 4, src:'./Tools/framer.svg', alt:'Framer'},
    {id: 5, src:'./Tools/gdsc.svg', alt:'Comunidad de Desarrolladores de Google'},
    {id: 6, src:'./Tools/github_dark.svg', alt:'GitHub'},
    {id: 7, src:'./Tools/gitlab.svg', alt:'GitLab'},
    {id: 8, src:'./Tools/google_ads-icon.svg', alt:'Google Ads'},
    {id: 9, src:'./Tools/Google_Colaboratory (1).svg', alt:'Google Colaboratory'},
    {id: 10, src:'./Tools/kubernetes.svg', alt:'Kubernetes'},
    {id: 11, src:'./Tools/motion_dark.svg', alt:'Motion'},
    {id: 12, src:'./Tools/npm-wordmark.svg', alt:'npm'},
    {id: 13, src:'./Tools/prisma_dark.svg', alt:'Prisma'},
    {id: 14, src:'./Tools/SISS.svg', alt:'SISS'},
    {id: 15, src:'./Tools/trello.svg', alt:'Trello'},
    {id: 17, src:'./Tools/visual-studio.svg', alt:'Visual Studio'},
    {id: 18, src:'./Tools/vscode.svg', alt:'VSCode'},
    {id: 19, src:'./Tools/supabase.svg', alt:'Supabase'},
    {id: 17, src:'./Frameworks/laravel.svg', alt:'Laravel'},
    {id: 18, src:'./Frameworks/nestjs.svg', alt:'NestJS'},
    {id: 19, src:'./Frameworks/nextjs_icon_dark.svg', alt:'NextJS'},
    {id: 20 , src: './Tools/microsoft-excel.svg', alt: 'Microsoft Excel'},
    {id: 25, src:'./Tools/Semrush.svg', alt:'Semrush'},
    {id: 26, src:'./Tools/Ubersuggest.svg', alt:'Ubersuggest'},

    
];